repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.3
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-install
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-shebang-scripts-are-executable
  - id: pretty-format-json
    args: [--autofix]
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: forbid-submodules
  - id: mixed-line-ending
  - id: name-tests-test
    args: [--pytest-test-first]
  - id: trailing-whitespace
    description: Trims trailing whitespace.
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.3.0
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: ["-c", "pyproject.toml"]
    additional_dependencies: ["bandit[toml]"]
    description: Checks Python files for security issues.
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  - id: absolufy-imports
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
  - id: commitizen
    description: Checks that git commit messages are standartized.
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-toml
    additional_dependencies: [setuptools]
    args: [--autofix]
  - id: pretty-format-yaml
    additional_dependencies: [setuptools]
    args: [--autofix, --indent, "2", --preserve-quotes]
- repo: local
  hooks:
  - id: render-kubernetes-manifests
    name: render-kubernetes-manifests
    entry: just render-kubernetes-manifests
    language: system
    pass_filenames: false
