version: "3.7"

services:
  scylla:
    image: scylladb/scylla
    volumes:
      - /var/lib/scylla:/var/lib/scylla
    ports:
      - "9042:9042"
      - "9160:9160"
      - "9180:9180"
      - "10000:10000"